import {
  IconPlayerPlay,
  IconPlayerTrackNext,
  IconPlayerTrackPrev,
  IconCheck,
  IconCircleCheck,
  IconCircleX,
  IconBan,
  IconCalendar,
  IconCalendarPlus,
  IconCalendarCheck,
  IconDownload,
  IconCloudDownload,
  IconStar,
  IconStarFilled,
  IconHeart,
  IconHeartFilled,
  IconBookmark,
  IconBookmarkFilled,
  IconTag,
  IconTags,
  IconEye,
  IconEyeOff,
  IconPencil,
  IconEdit,
  IconTrash,
  IconArchive,
  IconArchiveOff,
  IconBell,
  IconBellRinging,
  IconFlag,
  IconFlagFilled,
  IconPin,
  IconPinned,
  IconSend,
  IconRefresh,
  IconClock,
  IconHourglass,
} from '@tabler/icons-react'
import type { ComponentType } from 'react'

export interface IconOption {
  name: string       // stored in ActionButton.icon
  component: ComponentType<{ size?: number | string }>
}

export const ICON_OPTIONS: IconOption[] = [
  { name: 'IconPlayerPlay',      component: IconPlayerPlay },
  { name: 'IconPlayerTrackNext', component: IconPlayerTrackNext },
  { name: 'IconPlayerTrackPrev', component: IconPlayerTrackPrev },
  { name: 'IconCheck',           component: IconCheck },
  { name: 'IconCircleCheck',     component: IconCircleCheck },
  { name: 'IconCircleX',         component: IconCircleX },
  { name: 'IconBan',             component: IconBan },
  { name: 'IconCalendar',        component: IconCalendar },
  { name: 'IconCalendarPlus',    component: IconCalendarPlus },
  { name: 'IconCalendarCheck',   component: IconCalendarCheck },
  { name: 'IconDownload',        component: IconDownload },
  { name: 'IconCloudDownload',   component: IconCloudDownload },
  { name: 'IconStar',            component: IconStar },
  { name: 'IconStarFilled',      component: IconStarFilled },
  { name: 'IconHeart',           component: IconHeart },
  { name: 'IconHeartFilled',     component: IconHeartFilled },
  { name: 'IconBookmark',        component: IconBookmark },
  { name: 'IconBookmarkFilled',  component: IconBookmarkFilled },
  { name: 'IconTag',             component: IconTag },
  { name: 'IconTags',            component: IconTags },
  { name: 'IconEye',             component: IconEye },
  { name: 'IconEyeOff',          component: IconEyeOff },
  { name: 'IconPencil',          component: IconPencil },
  { name: 'IconEdit',            component: IconEdit },
  { name: 'IconTrash',           component: IconTrash },
  { name: 'IconArchive',         component: IconArchive },
  { name: 'IconArchiveOff',      component: IconArchiveOff },
  { name: 'IconBell',            component: IconBell },
  { name: 'IconBellRinging',     component: IconBellRinging },
  { name: 'IconFlag',            component: IconFlag },
  { name: 'IconFlagFilled',      component: IconFlagFilled },
  { name: 'IconPin',             component: IconPin },
  { name: 'IconPinned',          component: IconPinned },
  { name: 'IconSend',            component: IconSend },
  { name: 'IconRefresh',         component: IconRefresh },
  { name: 'IconClock',           component: IconClock },
  { name: 'IconHourglass',       component: IconHourglass },
]

export function getIconComponent(name: string | undefined): ComponentType<{ size?: number | string }> | null {
  if (!name) return null
  return ICON_OPTIONS.find(o => o.name === name)?.component ?? null
}
